spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: RegisterService
          uri: http://localhost:8082
          predicates:
            - Path=/api/register/**
        - id: LoginService
          uri: http://localhost:8083
          predicates:
            - Path=/api/login/**